### ISSUE TITLE
Can't find Nginx at Localhost

### ISSUE THREAD

**Issue by robbyemmert** [pie-inc/docker-wordpress-multisite#1]
Awesome repository, thanks for cataloging WordPress Multisite docker config!

I'm getting no response at localhost:8080 after bringing docker-compose up. All services are running. I have no custom settings or environment variables.

Any ideas?

**Comment by offeringofpie** [comment]
Hi sorry for only reading this now. I'll be updating this weekend to address that issue.
The reason it wasn't working is because I was using `wordpress.local` (added to `/etc/hosts`).

Stay tuned
